[package]
name = "alloy-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.15", features = ["full"] }
tokio = { version = "1.38.2", features = ["full"] }
dotenv = "0.15"
log = "0.4.21"
env_logger = "0.11.3"
eyre = "0.6.12"
bigdecimal = "0.4"
